project_id = "ptisltjfqomavvlnghcm"

[functions.analyze-pill]
verify_jwt = false

[functions.import-pill-data]
verify_jwt = false

[functions.enrich-drug-info]
verify_jwt = false

[functions.find-treatment]
verify_jwt = false

[functions.check-interactions]
verify_jwt = false

[functions.sync-rximage-data]
verify_jwt = false
[functions.sync-nps-alerts]
verify_jwt = false

[functions.import-testri]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.purge-anon-images]
verify_jwt = true
