-- 1. Remove the overly permissive public SELECT on counterfeit_reports base table
-- The counterfeit_reports_public VIEW (created by postgres/superuser) bypasses RLS
-- and already strips sensitive columns (location_lat, location_lng, notes, photo_url)
DROP POLICY IF EXISTS "Public can view safe counterfeit data" ON public.counterfeit_reports;

-- 2. Add storage RLS policies for pill-images bucket

-- Allow authenticated users to SELECT their own uploaded files
CREATE POLICY "Users can view own pill images"
ON storage.objects
FOR SELECT
TO authenticated
USING (
  bucket_id = 'pill-images'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Allow service role (edge functions) to read any pill image
-- Anonymous users who uploaded get access via signed URLs generated by edge functions

-- Allow authenticated users to delete their own uploaded files
CREATE POLICY "Users can delete own pill images"
ON storage.objects
FOR DELETE
TO authenticated
USING (
  bucket_id = 'pill-images'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Allow authenticated users to update their own uploaded files
CREATE POLICY "Users can update own pill images"
ON storage.objects
FOR UPDATE
TO authenticated
USING (
  bucket_id = 'pill-images'
  AND (storage.foldername(name))[1] = auth.uid()::text
);